### ISSUE TITLE
1.0.0-rc52 crash when contacts add

### ISSUE THREAD

**Issue by flyskywhy** [textileio/go-textile#614]
With go-textile_v1.0.0-rc52_linux-amd64.tar.gz
```
$ textile contacts add -p 12D3KooW9sxYAEHH45ySJV1qeK4Dsn6zyFujcrw2pDKT1VZeNwie
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x184f750]

goroutine 20761 [running]:
github.com/textileio/go-textile/core.(*CafeService).searchLocal(0xc000082900, 0x1, 0xc0024d1f40, 0xc00263a370, 0x1, 0xc003588000, 0x14, 0x1000)
	/go/src/github.com/textileio/go-textile/core/cafe_service.go:636 +0x1a0
github.com/textileio/go-textile/core.(*Textile).search.func1(0xc0026ce840, 0x2, 0x2, 0xc0001e08c0, 0xc0019ff200, 0xc002587aa0, 0xc002587920, 0x3fca418, 0x0, 0x0, ...)
	/go/src/github.com/textileio/go-textile/core/search.go:110 +0xb7
created by github.com/textileio/go-textile/core.(*Textile).search
	/go/src/github.com/textileio/go-textile/core/search.go:102 +0x581
Post http://127.0.0.1:40600/api/v0/contacts/search: EOF
No contacts were found
[1]+  Exit 2                  textile daemon
```

**Comment by sanderpick** [comment]
Thanks for the report @flyskywhy. Are you by chance trying to add yourself as a contact? If so, I see the issue. 

FYI: I'll be removing searching / adding contacts by peer ID in the next release. An account can have multiple peers. It doesn't make sense to only add one of them. So, search by address or fuzzy username will be the way moving forward.

**Comment by flyskywhy** [comment]
You're right, I check my shell history, crash happened when add myself as a contact, and also will happen on 1.00-rc51. If add other as a contact, there is no problem.
