### ISSUE TITLE
Contact search is causing a crash

### ISSUE THREAD

**Issue by andrewxhill** [textileio/go-textile#653]
@andrewxhill commented on [Mon Mar 25 2019](https://github.com/textileio/textile-mobile/issues/988)

Verified on ios + android, production and beta

Got to Contacts, click "+" to add, start typing to search.

Crashes

**Comment by andrewxhill** [comment]
```
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: panic: close of closed channel
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: goroutine 15277 [running]:
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: github.com/textileio/go-textile/broadcast.(*Broadcaster).Close(0x8b844340)
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go:     /home/circleci/go/src/github.com/textileio/go-textile/broadcast/main.go:54 +0x94
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: github.com/textileio/go-textile/core.(*Textile).search.func1.3.1(0x8be8f4d0)
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go:     /home/circleci/go/src/github.com/textileio/go-textile/core/search.go:161 +0x104
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: github.com/textileio/go-textile/core.(*CafeService).Search(0x89608780, 0x8bc9adb0, 0x8ab1e360, 0x26, 0x8c821f98, 0x8b519180, 0x0, 0x0)
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go:     /home/circleci/go/src/github.com/textileio/go-textile/core/cafe_service.go:450 +0x1dc
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go: github.com/textileio/go-textile/core.(*Textile).search.func1.3(0x8b916e10, 0x8c1f73e0, 0x8963e000, 0x8b7acc10, 0x8c194208, 0x1, 0x2, 0x8b844340, 0x8abbb540, 0x0, ...)
2019-03-25 18:41:05.741 22586-0/com.textile.dev E/Go:     /home/circleci/go/src/github.com/textileio/go-textile/core/search.go:156 +0xf4
2019-03-25 18:41:05.742 22586-0/com.textile.dev E/Go: created by github.com/textileio/go-textile/core.(*Textile).search.func1
2019-03-25 18:41:05.742 22586-0/com.textile.dev E/Go:     /home/circleci/go/src/github.com/textileio/go-textile/core/search.go:150 +0x2cc
2019-03-25 18:41:05.742 22586-22789/com.textile.dev A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 22789 (pool-3-thread-1), pid 22586 (com.textile.dev)
```
