### ISSUE TITLE
requizzle causing build-js-type job to fail

### ISSUE THREAD

**Issue by sanderpick** [textileio/go-textile#729]
```
circleci@908f78e49e72:~/project$ ./node_modules/protobufjs/bin/pbts -o protos/index.d.ts protos/index.js
/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:45
    if (lookupPaths[0] === targetPath && lookupPaths[1].length === 0) {
                   ^

TypeError: Cannot read property '0' of null
    at isNativeModule (/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:45:17)
    at Requizzle.requizzle (/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/requizzle.js:82:6)
    at infectProxy (/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:82:28)
    at Module.targetModule.require (/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:101:11)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/circleci/project/node_modules/protobufjs/cli/node_modules/jsdoc/lib/jsdoc/fs.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Object.load (/home/circleci/project/node_modules/protobufjs/cli/node_modules/requizzle/lib/loader.js:112:15)
/home/circleci/project/node_modules/protobufjs/cli/pbts.js:133
                throw err;
                ^

Error: code 1
    at ChildProcess.<anonymous> (/home/circleci/project/node_modules/protobufjs/cli/pbts.js:130:27)
    at ChildProcess.emit (events.js:201:15)
    at maybeClose (internal/child_process.js:1000:16)
    at Socket.<anonymous> (internal/child_process.js:405:11)
    at Socket.emit (events.js:196:13)
    at Pipe.<anonymous> (net.js:586:12)
```

**Comment by sanderpick** [comment]
Needed a newer, unreleased, version of requizzle in jsdoc. So, forked and added that... then pulled our package into protobuf.js:

- https://github.com/textileio/protobuf.js/commit/2e4a9ac199e2d93df30ff2ff4c470792b0d2490c
- https://github.com/textileio/protobuf.js/commit/3300f19502b45bd485c5702310c5edd7bc8a784b
